# Generated by Django 4.2 on 2023-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstmyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'technologies_database',
            },
        ),
        migrations.AlterModelTable(
            name='mobile_technology_waves',
            table='mobile_technology_database',
        ),
    ]
